name: physics_ease_release
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 2.2.0+17

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_avif: ^3.1.0
  flutter_math_fork: ^0.7.4
  share_plus: ^7.2.1
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.10
  google_generative_ai: ^0.2.2
  http: ^1.2.1
  math_expressions: ^2.1.0
  path_provider: ^2.1.3
  sensors_plus: ^5.0.1
  fl_chart: ^0.68.0
  permission_handler: ^11.3.1
  flutter_launcher_icons: ^0.13.1
  screenshot: ^3.0.0
  introduction_screen: ^4.0.0
  vector_math: ^2.1.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/kinematica.json
    - assets/dinamica.json
    - assets/termodinamica.json
    - assets/lavoro.json
    - assets/elettrostatica.json
    - assets/elettromagnetismo.json
    - assets/ottica.json
    - assets/fluidi.json
    - assets/gravitazione.json
    - assets/qmoto.json
    - assets/momentoangolare.json
    - assets/circuiti.json
    - assets/magnetismo.json
    - assets/relativita.json
    - assets/fisicaquantistica.json
    - assets/fisicanucleare.json
    - assets/my_logo.png
    - assets/my_logo_dark.png
    - assets/my_logo_light.png
    - assets/planet/sun.png
    - assets/planet/earth.png
    - assets/planet/moon.png
    - assets/planet/jupiter.png
    - assets/planet/mars.png
    - assets/planet/neptune.png
    - assets/planet/venus.png
    - assets/planet/uranus.png
    - assets/planet/saturn.png
    - assets/planet/mercury.png
    - assets/planet/pluto.png
    - assets/fisici/AbdusSalam.avif
    - assets/fisici/AlbertEinstein.avif
    - assets/fisici/CharlesAugustinDeCoulomb.avif
    - assets/fisici/ChristiaanHuygens.avif
    - assets/fisici/DanielBernoulli.avif
    - assets/fisici/EnricoFermi.avif
    - assets/fisici/ErnestRutherford.avif
    - assets/fisici/ErwinSchrödinger.avif
    - assets/fisici/HeinrichHertz.avif
    - assets/fisici/HenryCavendish.avif
    - assets/fisici/JamesClerkMaxwell.avif
    - assets/fisici/LeonhardEuler.avif
    - assets/fisici/MarieCurie.avif
    - assets/fisici/MaxPlanck.avif
    - assets/fisici/MichaelFaraday.avif
    - assets/fisici/NielsBohr.avif
    - assets/fisici/PaulDirac.avif
    - assets/fisici/PeterHiggs.avif
    - assets/fisici/RichardFeynman.avif
    - assets/fisici/RobertHooke.avif
    - assets/fisici/StevenWeinberg.avif
    - assets/fisici/WernerHeisenberg.avif
    - assets/fisici/WolfgangPauli.avif
    - assets/fisici/Archimede.avif
    - assets/fisici/IsaacNewton.avif
    - assets/fisici/GalileoGalilei.avif
    - assets/fisici/JohannesKepler.avif
    - assets/fisici/EvangelistaTorricelli.avif
    - assets/fisici/BlaisePascal.avif
    - assets/fisici/RobertBoyle.avif
    - assets/fisici/EtienneLouisMalus.avif
    - assets/fisici/AndreMarieAmpere.avif
    - assets/fisici/JeanBaptisteJosephFourier.avif
    - assets/fisici/CarlFriedrichGauss.avif
    - assets/fisici/JosephLouisGayLussac.avif
    - assets/fisici/GeorgSimonOhm.avif
    - assets/fisici/SadiCarnot.avif
    - assets/fisici/FranzErnstNeumann.avif
    - assets/fisici/HeinrichLenz.avif
    - assets/fisici/JamesPrescottJoule.avif
    - assets/fisici/GeorgeGabrielStokes.avif
    - assets/fisici/RudolfClausius.avif
    - assets/fisici/LordKelvin.avif
    - assets/fisici/GustavRobertKirchhoff.avif
    - assets/fisici/JosephStefan.avif
    - assets/fisici/OsborneReynolds.avif
    - assets/fisici/LudwigBoltzmann.avif
    - assets/fisici/HendrikAntoonLorentz.avif
    - assets/fisici/WilhelmWien.avif
    - assets/fisici/LouisDeBroglie.avif
    - assets/fisici/ArthurCompton.avif
    - assets/fisici/JohnHenryPoynting.avif

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  image_path_ios: "assets/icon/PhysicsEase_icon_light.png"
  #image_path_ios_dark_transparent: "assets/icon/PhysicsEase_icon_dark.png"
  remove_alpha_ios: true
  min_sdk_android: 21           # La versione minima dell'SDK Android supportata
  # adaptive_icon_foreground: "assets/icon/foreground.png" # Opzionale per icone adattive Android
  adaptive_icon_background: "#FEFFFF" # Opzionale per icone adattive Android (può essere un colore o un percorso immagine)
  # ios_content_mode: "scaleAspectFit" # Opzionale: come l'icona si adatta

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
